/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects/index'
import { Route as LayoutProjectsProjectIdIndexRouteImport } from './routes/_layout/projects/$projectId/index'
import { Route as LayoutProjectsProjectIdTasksRouteImport } from './routes/_layout/projects/$projectId/tasks'
import { Route as LayoutProjectsProjectIdRepositoriesRouteImport } from './routes/_layout/projects/$projectId/repositories'
import { Route as LayoutProjectsProjectIdMeetingsRouteImport } from './routes/_layout/projects/$projectId/meetings'
import { Route as LayoutProjectsProjectIdMeetingsMeetingIdRouteImport } from './routes/_layout/projects/$projectId/meetings.$meetingId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProjectIdIndexRoute =
  LayoutProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsProjectIdTasksRoute =
  LayoutProjectsProjectIdTasksRouteImport.update({
    id: '/projects/$projectId/tasks',
    path: '/projects/$projectId/tasks',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsProjectIdRepositoriesRoute =
  LayoutProjectsProjectIdRepositoriesRouteImport.update({
    id: '/projects/$projectId/repositories',
    path: '/projects/$projectId/repositories',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsProjectIdMeetingsRoute =
  LayoutProjectsProjectIdMeetingsRouteImport.update({
    id: '/projects/$projectId/meetings',
    path: '/projects/$projectId/meetings',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProjectsProjectIdMeetingsMeetingIdRoute =
  LayoutProjectsProjectIdMeetingsMeetingIdRouteImport.update({
    id: '/$meetingId',
    path: '/$meetingId',
    getParentRoute: () => LayoutProjectsProjectIdMeetingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof LayoutIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/projects/$projectId/meetings': typeof LayoutProjectsProjectIdMeetingsRouteWithChildren
  '/projects/$projectId/repositories': typeof LayoutProjectsProjectIdRepositoriesRoute
  '/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdIndexRoute
  '/projects/$projectId/meetings/$meetingId': typeof LayoutProjectsProjectIdMeetingsMeetingIdRoute
}
export interface FileRoutesByTo {
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof LayoutIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/projects/$projectId/meetings': typeof LayoutProjectsProjectIdMeetingsRouteWithChildren
  '/projects/$projectId/repositories': typeof LayoutProjectsProjectIdRepositoriesRoute
  '/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/projects/$projectId': typeof LayoutProjectsProjectIdIndexRoute
  '/projects/$projectId/meetings/$meetingId': typeof LayoutProjectsProjectIdMeetingsMeetingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/projects/$projectId/meetings': typeof LayoutProjectsProjectIdMeetingsRouteWithChildren
  '/_layout/projects/$projectId/repositories': typeof LayoutProjectsProjectIdRepositoriesRoute
  '/_layout/projects/$projectId/tasks': typeof LayoutProjectsProjectIdTasksRoute
  '/_layout/projects/$projectId/': typeof LayoutProjectsProjectIdIndexRoute
  '/_layout/projects/$projectId/meetings/$meetingId': typeof LayoutProjectsProjectIdMeetingsMeetingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/callback'
    | '/auth/login'
    | '/'
    | '/projects'
    | '/projects/$projectId/meetings'
    | '/projects/$projectId/repositories'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId'
    | '/projects/$projectId/meetings/$meetingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/callback'
    | '/auth/login'
    | '/'
    | '/projects'
    | '/projects/$projectId/meetings'
    | '/projects/$projectId/repositories'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId'
    | '/projects/$projectId/meetings/$meetingId'
  id:
    | '__root__'
    | '/_layout'
    | '/auth/callback'
    | '/auth/login'
    | '/_layout/'
    | '/_layout/projects/'
    | '/_layout/projects/$projectId/meetings'
    | '/_layout/projects/$projectId/repositories'
    | '/_layout/projects/$projectId/tasks'
    | '/_layout/projects/$projectId/'
    | '/_layout/projects/$projectId/meetings/$meetingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/': {
      id: '/_layout/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof LayoutProjectsProjectIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/tasks': {
      id: '/_layout/projects/$projectId/tasks'
      path: '/projects/$projectId/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof LayoutProjectsProjectIdTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/repositories': {
      id: '/_layout/projects/$projectId/repositories'
      path: '/projects/$projectId/repositories'
      fullPath: '/projects/$projectId/repositories'
      preLoaderRoute: typeof LayoutProjectsProjectIdRepositoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/meetings': {
      id: '/_layout/projects/$projectId/meetings'
      path: '/projects/$projectId/meetings'
      fullPath: '/projects/$projectId/meetings'
      preLoaderRoute: typeof LayoutProjectsProjectIdMeetingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$projectId/meetings/$meetingId': {
      id: '/_layout/projects/$projectId/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/projects/$projectId/meetings/$meetingId'
      preLoaderRoute: typeof LayoutProjectsProjectIdMeetingsMeetingIdRouteImport
      parentRoute: typeof LayoutProjectsProjectIdMeetingsRoute
    }
  }
}

interface LayoutProjectsProjectIdMeetingsRouteChildren {
  LayoutProjectsProjectIdMeetingsMeetingIdRoute: typeof LayoutProjectsProjectIdMeetingsMeetingIdRoute
}

const LayoutProjectsProjectIdMeetingsRouteChildren: LayoutProjectsProjectIdMeetingsRouteChildren =
  {
    LayoutProjectsProjectIdMeetingsMeetingIdRoute:
      LayoutProjectsProjectIdMeetingsMeetingIdRoute,
  }

const LayoutProjectsProjectIdMeetingsRouteWithChildren =
  LayoutProjectsProjectIdMeetingsRoute._addFileChildren(
    LayoutProjectsProjectIdMeetingsRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
  LayoutProjectsProjectIdMeetingsRoute: typeof LayoutProjectsProjectIdMeetingsRouteWithChildren
  LayoutProjectsProjectIdRepositoriesRoute: typeof LayoutProjectsProjectIdRepositoriesRoute
  LayoutProjectsProjectIdTasksRoute: typeof LayoutProjectsProjectIdTasksRoute
  LayoutProjectsProjectIdIndexRoute: typeof LayoutProjectsProjectIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
  LayoutProjectsProjectIdMeetingsRoute:
    LayoutProjectsProjectIdMeetingsRouteWithChildren,
  LayoutProjectsProjectIdRepositoriesRoute:
    LayoutProjectsProjectIdRepositoriesRoute,
  LayoutProjectsProjectIdTasksRoute: LayoutProjectsProjectIdTasksRoute,
  LayoutProjectsProjectIdIndexRoute: LayoutProjectsProjectIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
